#!/bin/sh

self="`readlink -f "$0" 2>/dev/null || realpath "$0"`"
base_dir="`dirname "$self"`/.."

shopt -u xpg_echo
source "$base_dir/../medic-core/scripts/include/rearrange"

rename()
{
  find . -type d -exec chmod 755 {} \; &&
    chown -R root:wheel . &&
  \
  for pkg in pv zlib; do
    ln -s "../../medic-core/source/$pkg" "$pkg"
  done &&
  \
  local version="`find_version open-vm-tools-*.tar.*`" &&
  local source="`find * -prune -type d -name 'open-vm-tools-*'`" &&
  mv "$source" "open-vm-tools-$version"
}

apply_patches()
{
  (cd procps && patch -s -p1 \
    < ../../patches/procps-3.2.8-makefile-include.diff) &&
  (cd open-vm-tools && patch -s -p1 \
    < ../../patches/open-vm-tools-9.2.2-configure-cflags.diff) &&
  (cd open-vm-tools && patch -s -p1 \
    < ../../patches/open-vm-tools-9.4.0-linux-3.10.diff) &&
  (cd open-vm-tools && patch -s -p1 \
    < ../../patches/open-vm-tools-9.4.0-depmod-base-path.diff)
}

finished_path="$base_dir/../../status/vm-tools.finished"

if [ -f "$finished_path" ]; then
  echo "Tree already rearranged for collection 'vm-tools'; skipping" >&2
  exit 0
fi

cd "$base_dir/incoming" &&
\
echo -n "Renaming directories... " >&2 &&
  rename && echo 'done.' >&2 &&
echo -n "Removing compressed files... " >&2 &&
  remove && echo 'done.' >&2 &&
echo -n "Creating symbolic links... " >&2 &&
  symlink && echo 'done.' >&2 &&
echo -n "Applying patches... " >&2 &&
  apply_patches && echo 'done.' >&2 &&
\
touch "$finished_path"

