#!/bin/bash

set -o pipefail

prefix="$1"

if ! [ -d "$prefix" ]; then
  echo "Usage: $0 <prefix>" >&2
  exit 111
fi

up='../../../../..'

(cd "$prefix" &&
  rm -rf \
    Library usr lib/perl5 lib/engines lib/*.la \
    lib/*.a lib/*.py bin/*.py lib/python?.? lib/erlang/usr \
    lib/erlang/Install info include man java/manual share/man \
    share/gtk-doc share/doc doc logs html share/info share/emacs \
    etc/ssh_host* libexec/ssh-keysign usr/share/man etc/ssl/man) &&
\
(cd "$prefix/lib/erlang/lib" && mkdir -p .save &&
  mv asn1-* crypto-* compiler-* inets-* kernel-* os_mon-* public_key-* \
    sasl-* ssl-* stdlib-* tools-* syntax_tools-* xmerl-* .save &&
      rm -rf * && mv .save/* . && rmdir .save) &&
\
(cd "$prefix/java/bin" && 
  rm -f runant.p? *.bat *.cmd m2.conf) &&
\
(cd "$prefix/java/lib" && 
  rm -f ooxml-schemas-*.jar \
    vorbis-java-*.jar poi-*.jar xmlbeans-*.jar dom4j-*.jar \
    rome-*.jar pdfbox-*.jar jdom-*.jar pdfbox-*.jar fontbox-*.jar \
    jempbox-*.jar tagsoup-*.jar javaassist-*.jar isoparser-*.jar \
    scannotation-*.jar ant*.jar ant*.pom maven*.jar aether-*.jar \
    tika-*.jar bcprov-*.jar bcmail-*.jar netcdf-*.jar bcprov-*.jar) &&
\
(cd "$prefix" &&
  rm -rf etc/ssh &&
    ln -sf "$up/settings/medic-core/openssh" etc/ssh &&
  rm -rf etc/nginx &&
    ln -sf "$up/settings/medic-core/nginx" etc/nginx &&
  rm -rf var/log/nginx &&
    ln -sf "$up/../storage/medic-core/nginx/logs" var/log/nginx &&
  rm -rf var/run/nginx &&
    ln -sf "$up/../storage/medic-core/nginx/state" var/run/nginx &&
  rm -rf etc/couchdb &&
    ln -sf "$up/settings/medic-core/couchdb" etc/couchdb &&
  rm -rf var/log/couchdb &&
    ln -sf "$up/../storage/medic-core/couchdb/logs" var/log/couchdb &&
  rm -rf var/lib/couchdb &&
    ln -sf "$up/../storage/medic-core/couchdb/data" var/lib/couchdb &&
  rm -rf var/run/couchdb &&
    ln -sf "$up/../storage/medic-core/couchdb/state" var/run/couchdb &&
  rm -rf java/logs &&
    ln -sf "$up/storage/medic-core/couchdb-lucene/logs" java/logs &&
  rm -rf java/conf &&
    ln -sf "$up/settings/medic-core/couchdb-lucene" java/conf &&
  rm -rf java/indexes &&
    ln -sf "$up/storage/medic-core/couchdb-lucene/indexes" java/indexes) &&
\
(cd "$prefix/bin" &&
  rm -f gitk libusb.py jadmaker *-config node-gyp &&
  for binary in git-receive-pack git-upload-archive; do
    rm -f "$binary" && ln -sf git "$binary";
  done &&
  for binary in git git-cvsserver git-shell git-upload-pack; do
    rm -f "$binary" && ln -sf "../libexec/git-core/$binary" "$binary";
  done) &&
\
(cd "$prefix/lib" &&
  rm -rf erlang/erts-5.10.4/man) &&
\
(cd "$prefix/sbin" &&
  rm -f tcpdump.*) &&
\
(cd "$prefix/lib/node_modules" &&
  rm -rf node-gyp npm/man nodelint/man1) &&
\
(cd "$prefix/lib/node_modules/medic-transport/node_modules" &&
  rm -rf node-gammu-json && ln -sf ../../node-gammu-json)

