#!/bin/bash

set -o pipefail

self="`readlink -f "$0" 2>/dev/null || realpath "$0"`"
base_dir="`dirname "$self"`/.."

shopt -u xpg_echo
source "$base_dir/../medic-core/scripts/include/rearrange"

rename()
{
  find . -type d -exec chmod 755 {} \; &&
    chown -R root:root .
}

apply_patches()
{
  (cd busybox && patch -s -p1 \
    < ../../patches/busybox-depmod.diff) &&
  (cd linux && patch -s -p1 \
    < ../../patches/grsecurity-linux.diff) &&
  (cd linux && patch -s -p1 \
    < ../../patches/linux-final_putname.diff) &&
  (cd linux && patch -s -p1 \
    < ../../patches/linux-grsec-do_const.diff) &&
  (cd linux && patch -s -p1 \
    < ../../patches/linux-grsec-localversion.diff) &&
  (cd eudev && patch -s -p1 \
    < ../../patches/eudev-allow-missing-btrfs.diff) &&
  (cd dhcpcd && patch -s -p1 \
    < ../../patches/dhcpcd-configure-sa_family_t.diff)
}

finished_path="$base_dir/../../status/core.finished"

if [ -f "$finished_path" ]; then
  echo "Tree already rearranged for collection 'core'; skipping" >&2
  exit 0
fi

cd "$base_dir/incoming" &&
\
echo -n "Renaming directories... " >&2 &&
  rename && echo 'done.' >&2 &&
echo -n "Removing compressed files... " >&2 &&
  remove && echo 'done.' >&2 &&
echo -n "Creating symbolic links... " >&2 &&
  symlink && echo 'done.' >&2 &&
echo -n "Applying patches... " >&2 &&
  apply_patches && echo 'done.' >&2 &&
\
touch "$finished_path"

