#!/bin/bash

set -o pipefail

self="`readlink -f "$0" 2>/dev/null || realpath "$0"`"
base_dir="`dirname "$self"`/.."

source "$base_dir/scripts/include/logger" 2>/dev/null &&
source "$base_dir/scripts/include/builder" 2>/dev/null \
    || fatal 'Unable to load a required library'

main()
{
  return 0
}

fatal()
{
  echo "$0: fatal: $*" >&2
  exit 1
}

cd "$base_dir/source" && main "$@"
exit "$?"

