#!/bin/bash

set -o pipefail
shopt -u xpg_echo

self="`readlink -f "$0" 2>/dev/null || realpath "$0"`"
base_dir="`dirname "$self"`/.."

source "$base_dir/../medic-core/scripts/include/rearrange"

rename()
{
  true
}

apply_patches()
{
  true
}

finished_path="$base_dir/../../status/medic-couch2pg.finished"

if [ -f "$finished_path" ]; then
  echo "Tree already rearranged for 'medic-couch2pg'; skipping" >&2
  exit 0
fi

cd "$base_dir/incoming" &&
\
echo -n "Renaming directories... " >&2 &&
  rename && echo 'done.' >&2 &&
echo -n "Removing compressed files... " >&2 &&
  remove && echo 'done.' >&2 &&
echo -n "Creating symbolic links... " >&2 &&
  symlink && echo 'done.' >&2 &&
echo -n "Applying patches... " >&2 &&
  apply_patches && echo 'done.' >&2 &&
\
touch "$finished_path"

