#!/bin/bash

set -o pipefail

clean_all()
{
  for i in source/*; do
    if [ -h "$i" -a -f "$i/Makefile" ]; then
      ( cd "$i" && make clean && make distclean )
    fi
  done

  return 0
}

main()
{
  clean_all
}

main "$@"
exit $?

