#!/bin/bash

set -o pipefail
shopt -u xpg_echo

self="`readlink -f "$0" 2>/dev/null || realpath "$0"`"
base_dir="`dirname "$self"`/.."

source "$base_dir/../medic-core/scripts/include/rearrange"

rename()
{
  find . -type d -exec chmod 755 {} \; &&
    chown -R 0:0 . &&
  \
  for pkg in pv zlib; do
    ln -s "../../medic-core/source/$pkg" "$pkg"
  done
}

apply_patches()
{
  (cd procps && patch -s -p1 \
    < ../../patches/procps-3.2.8-glibc-p_pid.diff) &&
  (cd procps && patch -s -p1 \
    < ../../patches/procps-3.2.8-makefile-include.diff)
}

finished_path="$base_dir/../../status/vm-tools.finished"

if [ -f "$finished_path" ]; then
  echo "Tree already rearranged for 'vm-tools'; skipping" >&2
  exit 0
fi

cd "$base_dir/incoming" &&
\
echo -n "Renaming directories... " >&2 &&
  rename && echo 'done.' >&2 &&
echo -n "Removing compressed files... " >&2 &&
  remove && echo 'done.' >&2 &&
echo -n "Creating symbolic links... " >&2 &&
  symlink && echo 'done.' >&2 &&
echo -n "Applying patches... " >&2 &&
  apply_patches && echo 'done.' >&2 &&
\
touch "$finished_path"

