#!/bin/bash

check_args()
{
  true
}

clean_all()
{
  for i in *; do
    if [ -h "$i" -a -f "$i/Makefile" ]; then
      ( cd "$i" && make clean )
    fi
  done

  return 0
}

main()
{
  check_args "$@"
  clean_all
}

main "$@"
exit $?

