#!/bin/sh

log='/var/log/startup.log'
hypervisor_type="`cat /sys/hypervisor/type 2>/dev/null`"

log()
{
  echo -e "$*" >>"$log" 2>&1
}

print()
{
  if [ "$hypervisor_type" = 'xen' ]; then
    echo -e "$*" &>/dev/hvc0
  else
    echo -e "$*" >&2
  fi

  return "$?"
}

