#!/bin/bash

self="`realpath "$0" 2>/dev/null || readlink -f "$0"`" &&
dirname="`dirname "$self"`"

source "$dirname/include/utility"
source "$dirname/include/startup"

main()
{
  local root="$1"
  shift 1

  cd "$dirname" \
    || fatal "Failed to locate script; check permissions"

  exec "/boot/system-container-start"
  fatal 'Container start failed'
}

main "$@"
exit "$?"

