#!/bin/sh

source '/boot/include/utility'
network_config_base='/srv/system/settings/network'

main()
{
  local operation="$1"

  if [ $# -lt 1 ]; then
    usage
  fi

  shift 1

  case "$operation" in
    'static')
      apply_static_ip "$@" \
        || command_usage static_ip
      ;;
    'dns')
      apply_dns "$@" \
        || command_usage dns
      ;;
    'broadcast')
      apply_broadcast "$@" \
        || command_usage broadcast
      ;;
    'auto'|'automatic')
      apply_automatic_ip "$@" \
        || command_usage automatic_ip
      ;;
    '-h'|'--help')
      usage
      ;;
    *)
      fatal "Unknown operation '$operation'"
      ;;
  esac

  return "$?"
}

apply_static_ip()
{
  local ip="$1"
  local netmask="$2"
  local gateway="$3"

  if [ $# -ne 3 ]; then
    return 111
  fi

  mkdir -p "$network_config_base" &&
  \
  echo "$ip" > "$network_config_base/ip" &&
  echo '1' > "$network_config_base/static" &&
  echo "$netmask" > "$network_config_base/netmask" &&
  echo "$gateway" > "$network_config_base/gateway"

  return "$?"
}

apply_dns()
{
  if [ $# -le 0 ]; then
    return 111
  fi

  mkdir -p "$network_config_base" &&
  echo "$@" > "$network_config_base/dns"

  return "$?"
}

apply_broadcast()
{
  local broadcast="$1"

  if [ $# -ne 1 ]; then
    return 111
  fi

  mkdir -p "$network_config_base" &&
  echo "$broadcast" > "$network_config_base/broadcast"

  return "$?"
}

apply_automatic_ip()
{
  if [ $# -ne 0 ]; then
    return 111
  fi

  for key in ip netmask broadcast gateway dns static; do
    rm -f "$network_config_base/$key" || return "$?"
  done

  return 0
}

usage()
{
  echo "Usage:" >&2
  echo -n '  ' >&2 && usage_static_ip
  echo -n '  ' >&2 && usage_broadcast
  echo -n '  ' >&2 && usage_dns
  echo -n '  ' >&2 && usage_automatic_ip
  exit 111
}

usage_static_ip()
{
  echo "$0 static <ip-address> <netmask-ip> <gateway-ip>" >&2
}

usage_broadcast()
{
  echo "$0 broadcast <broadcast-ip>" >&2
}

usage_dns()
{
  echo "$0 dns <ip-address>..." >&2
}

usage_automatic_ip()
{
  echo "$0 auto" >&2
}

command_usage()
{
  local function="$1"

  echo 'Command usage:'
  echo -n '  ' >&2 && "usage_$function"
  exit 112
}

main "$@"
exit "$?"

