#!/bin/sh

source '/boot/include/utility'
source '/boot/include/package'
source '/boot/include/template'
source '/boot/include/manifest'
source '/boot/include/supervisor'

main()
{
  if [ $# -le 0 -o "$1" = '-h' -o "$1" = '--help' ]; then
    usage
  fi

  require_root
  supervisor_init

  local force_install=''

  if [ "$1" = '-f' -o "$1" = '--force' ]; then
    force_install='t'
    shift 1
  fi


  for path in "$@"; do
    local package="`package_extract_name "$path"`" \
      || fatal "Failed to determine name of package '$path'"

    package="`package_sanitize_name "$package"`" \
      || fatal "Package '$path' contains invalid name '$package'"

    if [ -z "$force_install" ]; then
      if package_is_installed "$package"; then
        fatal "Package '$package' is already installed"
      fi
    fi

    package_install "$path" \
      || fatal "Failed to install package '$path'"

    local rv="$?"

    if [ "$rv" -eq 253 ]; then
      info "Package '$package' has no services to start"
    elif [ "$rv" -ne 0 ]; then
      fatal "Failed to start supervisor for package '$package'"
    fi

    info "Package '$package' was successfully installed"
  done

  success 'All specified packages are installed'
  return 0
}

usage()
{
  echo "Usage: $0 [-f | --force] <package.vpkg>..." >&2
  exit 111
}

main "$@"
exit "$?"

