#!/bin/sh

source '/boot/include/utility'
source '/boot/include/package'
source '/boot/include/supervisor'
source '/boot/include/hypervisor'

main()
{
  local force_install=''

  if [ "$1" = '-f' -o "$1" = '--force' ]; then
    force_install='t'
    shift 1
  fi

  if [ $# -le 0 ]; then
    usage
  fi

  for package in "$@"; do
    package_update "$package" "$force_install" \
      || fatal "Failed to update package '$package'"
  done

  return 0
}

usage()
{
  echo "Usage: $0 [-f|--force] <package.vpkg>..." >&2
  exit 111
}

main "$@"
exit "$?"

