#!/bin/sh

source '/boot/include/utility'
source '/boot/include/package'
source '/boot/include/template'
source '/boot/include/supervisor'

main()
{
  if [ $# -le 0 ]; then
    usage
  fi

  require_root
  supervisor_init

  for path in "$@"; do
    local package="`package_extract_name "$path"`" \
      || fatal "Failed to determine name of package '$path'"

    package_install "$path" \
      || fatal "Failed to install package '$path'"

    package_setup "$package" \
      || fatal "Failed to run setup script for package '$path'"

    supervisor_start "$package"
    local rv="$?"

    if [ "$rv" -eq 253 ]; then
      info "Package '$package' has no services to start"
    elif [ "$rv" -ne 0 ]; then
      fatal "Failed to start supervisor for package '$package'"
    fi

    info "Package '$package' was successfully installed"
  done

  success 'All specified packages are installed'
  return 0
}

usage()
{
  echo "Usage: $0 <package.vpkg>..." >&2
  exit 111
}

main "$@"
exit "$?"

