#!/bin/sh

main()
{
  # Recovery console:
  #  Try to set sane environment variables. This is all self-contained,
  #  just in case files from the base system are missing or damaged.

  for pkg_path in /srv/software/*; do
    if [ -d "$pkg_path" ]; then
      local pkg="`basename "$pkg_path"`"
      for dir in bin sbin; do
        export PATH="$PATH:/srv/software/$pkg/current/default/$dir"
      done
    fi
  done

  # Set prompt:
  #  Again, include this verbatim rather than depend on /etc/profile.

  if [ "`id -u`" -eq 0 ]; then
    PS1='\e[1;31m\u\e[0m@\e[1;31m\h\e[0m:\e[1;34m\w\e[0m \$ '
  else
    PS1='\e[1;36m\u\e[0m@\e[1;36m\h\e[0m:\e[1;34m\w\e[0m \$ '
  fi

  # Set path:
  #  Include the service and package management scripts.

  export PATH="/boot:$PATH"

  exec /bin/sh - "$@"
  return "$?"
}

main "$@"
exit "$?"

