#!/bin/sh

source '/boot/include/utility'
source '/boot/include/supervisor'
source '/boot/include/hypervisor'

main()
{
  local package="`basename "$1"`"
  local attribute="$2"

  if [ "$package" = '-h' -o "$package" = '--help' ]; then
    usage
  fi

  if [ -z "$package" -o "$package" = 'all' ]; then
    supervisor_list_all_packages
  else
    if ! supervisor_package_exists "$package"; then
      fatal "Package '$package' is not currently installed"
    fi
    case "$attribute" in
      watched|expected|unexpected|enabled|disabled|running|restarting|down)
        ;;
      '')
        attribute='all' ;;
      *)
        fatal "Service attribute '$attribute' does not exist"
    esac
   
    "supervisor_list_${attribute}_services" "$package"
  fi

  if [ "$?" -ne 0 ]; then
    warn "Failed to one or more specified services"
  fi
  
  return "$?"
}

usage()
{
  echo -e "Usage:\n" \
    "  $0 <package-name | 'all'> [ status-name ]\n"
  echo
  echo -e "Supported status names:\n" \
    '  watched, (un)expected, [en|dis]abled, running, restarting, down' >&2

  exit 111
}

main "$@"
exit "$?"

