#!/bin/sh

source '/boot/include/utility'
source '/boot/include/supervisor'

usage()
{
  echo 'Usage:'
  echo "  $0 <package-name> [status-name]"
  echo
  echo 'Supported status names:'
  echo '  watched, expected, unexpected,'
  echo '  enabled, disabled, running, restarting, down' >&2

  exit 111
}

main()
{
  local package="`basename "$1"`"
  local attribute="$2"

  if [ "$package" = '-h' -o "$package" = '--help' ]; then
    usage
  fi

  require_root
  supervisor_init

  if [ -z "$package" -o "$package" = 'all' ]; then
    supervisor_list_all_packages
  else
    if ! supervisor_package_exists "$package"; then
      fatal "Package '$package' is not currently installed"
    fi
    case "$attribute" in
      watched|expected|unexpected|enabled|disabled|running|restarting|down)
        true ;;
      '')
        attribute='all' ;;
      *)
        fatal "Service attribute '$attribute' does not exist" ;;
    esac
   
    "supervisor_list_${attribute}_services" "$package"
  fi

  if [ "$?" -ne 0 ]; then
    warn "Failed to list one or more specified services"
  fi
  
  return "$?"
}

main "$@"
exit "$?"

