#!/bin/sh

source '/boot/include/utility'
source '/boot/include/supervisor'

enable()
{
  local package="$1"
  local service="$2"
  local is_wildcard="$3"

  # Sanity check:
  #   Make sure the service we're trying to enable actually exists.

  if ! supervisor_service_exists "$package" "$service"; then
    warn "Service '$package/$service' doesn't exist"
    return 1
  fi

  if [ "$is_wildcard" ]; then
    if supervisor_is_service_enabled "$package" "$service"; then
      warn "Service '$package/$service is already enabled; skipping"
      return 0
    fi
  fi

  supervisor_service_enable "$package" "$service" \
    || fatal "Failed to enable service '$package/$service'"

  info "Service '$package/$service' was enabled successfully"
  return 0
}

main()
{
  if [ "$#" -le 0 -o "$1" = '-h' -o "$1" = '--help' ]; then
    usage
  fi

  local package="$1"
  shift 1

  require_root
  supervisor_init

  local rv=''

  if [ "$#" -le 0 ]; then
    supervisor_list_all_services "$package" | while read service; do
      enable "$package" "$service" 't'
      local r="$?"; [ "$r" -eq 0 ] || exit "$r"
    done
    rv="$?"
  else
    for service in "$@"; do
      enable "$package" "$service"
      rv="$?"
    done
  fi

  if [ "$rv" -ne 0 ]; then
    fatal "Failed to enable one or more services in package '$package'"
  fi

  success "Finished enabling services in package '$package'"
  return 0
}

usage()
{
  echo "Usage: $0 <package-name> [service-name]..."
  exit 111
}

main "$@"
exit "$?"

