#!/bin/sh

source '/boot/include/utility'
source '/boot/include/supervisor'

main()
{
  if [ $# -le 0 ]; then
    usage
  fi

  require_root
  supervisor_init

  local package="$1"
  shift 1
  
  supervisor_start "$package" "$@"
  local rv="$?"

  if [ "$rv" -eq 253 ]; then
    warn "Package '$package' has no services to start"
  elif [ "$rv" -ne 0 ]; then
    warn "Failed to start one or more specified services"
  else
    success "Supervisor running for all services in package '$package'"
  fi

  return "$rv"
}

usage()
{
  echo "Usage: $0 <package-name> [service-name]..." >&2
  exit 111
}

main "$@"
exit "$?"

