#!/bin/sh

source '/boot/include/utility'
source '/boot/include/supervisor'

disable()
{
  local package="$1"
  local service="$2"
  local is_wildcard="$3"

  # Sanity check:
  #   Make sure the service we're trying to disable actually exists.

  if ! supervisor_service_exists "$package" "$service"; then
    return 1
  fi

  if [ "$is_wildcard" ]; then
    if supervisor_is_service_disabled "$package" "$service"; then
      warn "Service '$package/$service is already disabled; skipping"
      return 0
    fi
  fi

  supervisor_service_disable "$package" "$service" \
    || fatal "Failed to disable service '$package/$service'"

  info "Service '$package/$service' was disabled successfully"
  return 0
}

main()
{
  if [ "$#" -le 0 -o "$1" = '-h' -o "$1" = '--help' ]; then
    usage
  fi

  local package="$1"
  shift 1

  require_root
  supervisor_init

  package="`package_sanitize_name "$package"`" \
    || fatal "Invalid package name '$package'"

  local rv=''

  if [ "$#" -le 0 ]; then
    supervisor_list_all_services "$package" | while read service; do
      disable "$package" "$service" 't'
      local r="$?"; [ "$r" -eq 0 ] || exit "$r"
    done
    rv="$?"
  else
    for service in "$@"; do
      service="`service_sanitize_name "$service"`" \
        || fatal "Invalid service name '$service'"

      disable "$package" "$service"
      rv="$?"
    done
  fi

  if [ "$rv" -ne 0 ]; then
    fatal "Failed to disable one or more services in package '$package'"
  fi

  success "Finished disabling services in package '$package'"
  return 0
}

usage()
{
  echo "Usage: $0 <package-name> [service-name]..."
  exit 111
}

main "$@"
exit "$?"

