#!/bin/sh

source '/boot/include/utility'
source '/boot/include/supervisor'
source '/boot/include/hypervisor'

down()
{
  local package="$1"
  local service="$2"

  supervisor_service_down "$package" "$service" \
    || fatal "Failed to shut down service '$package/$service'"

  return 0
}

main()
{
  local package="$1"
  shift 1

  if [ -z "$package" ]; then
    usage
  fi

  if [ "$#" -le 0 ]; then
    supervisor_list_expected_services "$package" | while read service; do
      down "$package" "$service"
    done
  else
    for service in "$@"; do
      down "$package" "$service"
    done
  fi
    
  return 0
}

usage()
{
  echo "Usage: $0 <package-name> [service-name]..."
  exit 111
}

main "$@"
exit "$?"

