#!/bin/sh

source '/boot/include/utility'
source '/boot/include/supervisor'

disable()
{
  local package="$1"
  local service="$2"

  supervisor_service_disable "$package" "$service" \
    || fatal "Failed to disable service '$package/$service'"

  info "Service '$package/$service' disabled successfully"
  return 0
}

main()
{
  local package="$1"
  shift 1

  if [ -z "$package" ]; then
    usage
  fi

  require_root

  if [ "$#" -le 0 ]; then
    supervisor_list_expected_services "$package" | while read service; do
      disable "$package" "$service"
    done
  else
    for service in "$@"; do
      disable "$package" "$service"
    done
  fi

  if [ $# -le 0 ]; then
    success "All services in package '$package' are now disabled"
  else
    success "Selected services in package '$package' are now disabled"
  fi

  return 0
}

usage()
{
  echo "Usage: $0 <package-name> [service-name]..."
  exit 111
}

main "$@"
exit "$?"

