#!/bin/sh

source '/boot/include/utility'
source '/boot/include/supervisor'

enable()
{
  local package="$1"
  local service="$2"

  supervisor_service_enable "$package" "$service" \
    || fatal "Failed to enable service '$package/$service'"

  info "Service '$package/$service' enabled successfully"
  return 0
}

main()
{
  local package="$1"
  shift 1

  if [ -z "$package" ]; then
    usage
  fi

  require_root
  supervisor_init

  if [ "$#" -le 0 ]; then
    supervisor_list_disabled_services "$package" | while read service; do
      enable "$package" "$service"
    done
  else
    for service in "$@"; do
      enable "$package" "$service"
    done
  fi

  if [ $# -le 0 ]; then
    success "All services in package '$package' are now enabled"
  else
    success "Selected services in package '$package' are now enabled"
  fi
  return 0
}

usage()
{
  echo "Usage: $0 <package-name> [service-name]..."
  exit 111
}

main "$@"
exit "$?"

