#!/bin/sh

main()
{
  local prefix="$1"

  if ! [ -d "$prefix" ]; then
    echo "Usage: $0 <prefix>" >&2
    exit 111
  fi

  local assets_dir="`readlink -f ./garden-maker/assets`" \
    || return 111

  local images_dir="`readlink -f ./images`" \
    || return 111

  local unzip_dir='garden-futon-master'
  local logo_file='futon-logo-medic.png'

  (cd "$prefix/share/couchdb" &&
    \
    mkdir -p garden && cp "$assets_dir/dashboard.couch" garden &&
    \
    # unzip -qq "$assets_dir/futon.zip" &&
    # rm -rf www && mv "$unzip_dir/www" . && rm -rf "$unzip_dir" &&
    \
    cp "$images_dir/$logo_file" www/image/logo.png)

  return "$?"
}

main "$@"
exit "$?"

