#!/bin/bash

set -o pipefail

self="`readlink -f "$0" 2>/dev/null || realpath "$0"`"
source_base_dir="`dirname "$self"`/../"

source "$source_base_dir/medic-core/scripts/include/logger" \
    || fatal 'Unable to load logging library'

fatal()
{
  echo "$0: fatal: $*" >&2
  exit 1
}

usage()
{
  echo
  echo "Usage:" >&2
  echo "  $0 name platform command [args...]" >&2
  echo

  exit 111
}

check_args()
{
  local name="$1"
  local platform="$2"
  local command="$3"

  [ "$name" -a "$platform" -a "$command" ]
}

main()
{
  local name="$1"
  local platform="$2"
  shift 2

  check_args "$name" "$platform" "$@" || usage

  load_timestamp "$name" "$platform" \
    || fatal 'Unable to load last timestamp; retry from root directory'

  (exec sh -c "$*" 2>&1) | logger "$name" "$platform"
  return ${PIPESTATUS[0]}
}

main "$@"
exit "$?"

