#!/bin/bash

check_args()
{
  true
}

fix_modules()
{
  find open-vm-tools/modules/linux \
    -type f -a -name Makefile.kernel | while read path; do
  
    (cd "`dirname "$path"`" &&
      ln -sf Makefile.kernel Makefile.normal)
  done
}

clean_all()
{
  for i in *; do
    if [ -h "$i" -a -f "$i/Makefile" ]; then
      ( cd "$i" && make clean && make distclean )
    fi
  done
}

main()
{
  fix_modules
  check_args "$@"
  clean_all
}

main "$@"
exit $?

