#!/bin/sh

self="`readlink -f "$0" || realpath "$0"`"
base_dir="`dirname "$self"`/.."

source "$base_dir/../medic-core/scripts/include/rearrange"

rename()
{
  find . -type d -exec chmod 755 {} \; &&
    chown -R root:root . &&
	\
  local version="`find_version open-vm-tools-*.tar.*`" &&
  local source="`find * -prune -type d -name 'open-vm-tools-*'`" &&
  mv "$source" "open-vm-tools-$version"
}

apply_patches()
{
  (cd procps && patch -s -p1 < ../../patches/procps-3.2.8-makefile-include.diff)
}

cd "$base_dir/incoming" &&
\
echo -n "Renaming directories... " >&2 &&
  rename && echo 'done.' >&2 &&
\
echo -n "Removing compressed files... " >&2 &&
  remove && echo 'done.' >&2 &&
\
echo -n "Creating symbolic links... " >&2 &&
  symlink && echo 'done.' >&2 &&
\
echo -n "Applying patches... " >&2 &&
  apply_patches && echo 'done.' >&2

