#!/bin/sh

remove()
{
  rm -f *.downloaded *.finished &&
  rm -f *.tar.xz *.tar.lzma *.tar.bz2 *.tar.gz *.tgz
}

symlink()
{
  find * -prune -type d | while read dir; do
    ln -sf "$dir" "`echo "$dir" | sed 's/-[0-9\.a-z]\+$//;'`"
  done &&
  \
  for dir in logs stats; do
    ln -sf "../$dir" "$dir";
  done
}

find_version()
{
  echo "$@" | sed 's/^[A-Za-z0-9-]\+-v\?\([0-9\._]\+\).*$/\1/; s/\.$//;'
}

fix_version()
{
  echo "$@" | sed 's/^\([0-9]\)\([0-9]\)_\?\([0-9]\+\)/\1.\2.\3/;'
}

