#!/bin/sh

source '/boot/include/utility'
source '/boot/include/package'
source '/boot/include/supervisor'
source '/boot/include/hypervisor'

main()
{
  if [ $# -le 0 ]; then
    usage
  fi

  for path in "$@"; do

    local package="`package_extract_name "$path"`" \
      || fatal "Failed to determine name of package '$path'"

    package_install "$path" \
      || fatal "Failed to install package '$path'"

    package_setup "$package" \
      || fatal "Failed to run setup script for package '$path'"

    supervisor_start "$package" \
      || fatal "Failed to start supervisor for package '$package'"

  done

  return 0
}

usage()
{
  echo "Usage: $0 <package.vpkg>..." >&2
  exit 111
}

main "$@"
exit "$?"

