#!/bin/sh

source '/boot/include/utility'

main()
{
  if [ "$#" -le 0 ]; then
    usage
  fi

  for dir in "$@"; do
    if ! [ -d "$dir" ]; then
      continue
    fi
    for path in "$dir"/*; do
      if ! [ -x "$path" ]; then
        continue
      fi
      if ! "$path"; then
        local file="`basename "$path"`"
        warn "Script '$file' exited with non-zero status"
      fi
    done
  done

  return "$?"
}

usage()
{
  echo "Usage: $0 directory..." >&2
  exit 111
}

main "$@"
exit "$?"

