#!/bin/bash

self="`readlink -f "$0"`"
source_base_dir="`dirname "$self"`/../"

source "$source_base_dir/medic-core/scripts/include/logger" \
    || fatal 'Unable to load logging library'

fatal()
{
  echo "$0: fatal: $*" >&2
  exit 1
}

usage()
{
  echo
  echo "Usage:" >&2
  echo "  $0 name command [args...]" >&2
  echo

  exit 111
}

check_args()
{
  local name="$1"
  shift 1

  local command="$1"
  shift 1

  [ "$name" -a "$command" ]
}

main()
{
  local name="$1"
  shift 1

  check_args "$name" "$@" || usage

  load_timestamp "$name" \
    || fatal 'Unable to load last timestamp; retry from root directory'

  (exec sh -c "$*") 2>&1 | logger "$name"
  return ${PIPESTATUS[0]}
}

main "$@"
exit "$?"

