#!/bin/sh

source '/boot/include/package'
source '/boot/include/supervisor'

main()
{
  if [ $# -le 0 ]; then
    usage
  fi

  for package in "$@"; do
    package_remove "$package" \
      || fatal "Failed to remove package '$package'"
  done

  return 0
}

warn()
{
  echo "Warning: $*" 2>&1
}

fatal()
{
  echo "Fatal: $*" 2>&1
  exit 1
}

usage()
{
  echo "Usage: $0 <package-name>..." >&2
  exit 111
}

main "$@"
exit "$?"

