#!/bin/sh

source '/boot/include/supervisor'

main()
{
  local rv='0'

  if [ $# -le 0 ]; then
    usage
  fi

  for package in "$@"; do
    supervisor_stop "$package"
    local status="$?"
    
    if [ "$status" -ne 0 ]; then
      rv="$(($rv + $status))"
      warn "Failed to stop one or more services in package '$package'"
    fi
  done
  
  return "$rv"
}

warn()
{
  echo "Warning: $*" 2>&1
}

fatal()
{
  echo "Fatal: $*" 2>&1
  exit 1
}

usage()
{
  echo "Usage: $0 package-name..." >&2
  exit 111
}

main "$@"
exit "$?"


