#!/bin/sh

source '/boot/include/supervisor'

show_package()
{
  local package="`basename "$1"`"
  echo "Package '$package':"
  
}

show_services()
{
  local package="`basename "$1"`"
  local attributes='down expected watched running'

  local n="`supervisor_list_all_services "$package" | wc -l`"
  
  if [ "$?" -ne 0 -o "$n" -le 0 ]; then
    echo '  <No services are available in this package>'
    echo
    return 1
  fi
  
  supervisor_list_all_services "$@" | while read service; do
    echo "  Service '$service':"
    echo -n '    '

    # Try to give a meaningful short status    
    if supervisor_is_service_running "$package" "$service"; then
    	echo -n 'OK'
    elif supervisor_is_service_down "$package" "$service"; then
    	echo -n 'Stopped'
    else
    	echo -n 'Problem'
    fi
    
    echo -n ' ('

    # Dump all attributes out 
    for attribute in $attributes; do
      if "supervisor_is_service_$attribute" "$package" "$service"; then
        echo -n "$attribute "
      fi
    done | sed 's/ \([^$]\)/, \1/g; s/ $//;'
    echo ')'
  done
  
  echo
  return 0
}

main()
{
  echo
  
  if [ "$#" -gt 0 ]; then
    for package in "$@"; do
      show_package "$package"
      show_services "$package"
    done
  else
    supervisor_list_all_packages | while read package; do
      show_package "$package"
      show_services "$package"
    done
  fi
}

warn()
{
  echo "Warning: $*" >&2
}

fatal()
{
  echo "Fatal: $*" >&2
  exit 1
}

usage()
{
  echo "Usage: $0 [package-name]..." >&2
  exit 111
}

main "$@"
exit "$?"

