#!/bin/sh

source '/boot/include/supervisor'

main()
{
  local package="$1"
  shift 1
  
  if [ $# -le 0 -o -z "$package" ]; then
    usage
  fi

  for service in "$@"; do
    supervisor_service_up "$package" "$service" \
      || fatal "Failed to start service '$service' in '$package'"
  done
  
  return 0
}

warn()
{
  echo "Warning: $*" 2>&1
}

fatal()
{
  echo "Fatal: $*" 2>&1
  exit 1
}

usage()
{
  echo "Usage: $0 package-name service-name..."
  exit 111
}

main "$@"
exit "$?"

