#!/bin/sh

source '/boot/include/startup'
source '/boot/include/supervisor'

main()
{
  local numerator='0'
  local denominator='0'
  
  set_cursor 0 && set_console_blanking 0

  while true; do
    for i in `supervisor_list_all_packages`; do
      runnable_services="`supervisor_list_runnable_services "$i" | wc -l`"
      running_services="`supervisor_list_running_services "$i" | wc -l`"
      numerator="$(($numerator + running_services))"
      denominator="$(($denominator + runnable_services))"
    done
    echo -ne "$running_services / $runnable_services\r"
    sleep 1
  done

  set_cursor 1
  return 0
}

warn()
{
  echo "Warning: $*" 2>&1
}

fatal()
{
  echo "Fatal: $*" 2>&1

  sleep 10
  exit 1
}

main
exit "$?"

