#!/bin/sh

source '/boot/include/cursor'
source '/boot/include/startup'
source '/boot/include/supervisor'

main()
{
  local numerator='0'
  local denominator='0'
  
  set_echo 0
  set_cursor 0
  trap 'true' INT
  set_console_blanking 0

  while true; do
  
    local numerator='0';
    local denominator='0';
    
    for i in `supervisor_list_all_packages`; do
      local runnable_services="`supervisor_list_runnable_services "$i" | wc -l`"
      local running_services="`supervisor_list_running_services "$i" | wc -l`"
      
      numerator="$(($numerator + $running_services))"
      denominator="$(($denominator + $runnable_services))"
    done
    
    delta="$(($denominator - $numerator))"
      
    if [ "$delta" -le 0 ]; then
      display_centered "All services are running normally"
    else
      set_bold 1
      if [ "$delta" -gt 1 ]; then
        display_centered "There is a problem with $delta services"
      else
        display_centered "There is a problem with one service"
      fi
      set_bold 0
    fi
    
    sleep 1
    
  done

  return 0
}

warn()
{
  echo "Warning: $*" 2>&1
}

fatal()
{
  echo "Fatal: $*" 2>&1

  sleep 10
  exit 1
}

main
exit "$?"

