#!/bin/sh 

set -o pipefail

manifest_compare_generic()
{
  local previous_manifest="$1"
  local replacement_manifest="$2"
  local include_added="$3"
  local include_removed="$4"

  local p='[';

  if [ "$include_added" ]; then
    p="${p}+"
  fi

  if [ "$include_removed" ]; then
    p="${p}-"
  fi

  p="${p}]"

  diff -wdub "$previous_manifest" "$replacement_manifest" \
    | grep -v "^$p$p$p " | grep "^$p" | sed "s/^$p//;" | sort -r

  return "$?"
}

manifest_find_removed()
{
  manifest_compare_generic "$1" "$2" '' 't'
  return "$?"
}

manifest_find_added()
{
  manifest_compare_generic "$1" "$2" 't' ''
  return "$?"
}

manifest_find_differences()
{
  manifest_compare_generic "$1" "$2" 't' 't'
  return "$?"
}

manifest_filter()
{
  local directories="$1"

  if [ "$directories" ]; then
    grep '/$'
  else
    grep -v '/$'
  fi

  return "$?"
}

