#!/bin/bash

set -o pipefail

prefix="$1"

if ! [ -d "$prefix" ]; then
  echo "Usage: $0 <prefix>" >&2
  exit 111
fi

(cd "$prefix" &&
  rm -rf etc include man share/man share/doc \
    share/info share/dbus-1 share/glib-2.0 share/gtk-doc)

(cd "$prefix" &&
 rm -rf var/run/avahi-daemon &&
   ln -sf ../../../../../../storage/vm-tools/avahi/state var/run/avahi-daemon)

