#!/bin/bash

self="`readlink -f "$0" 2>/dev/null || realpath "$0"`"
base_dir="`dirname "$self"`/.."

fatal()
{
  echo "Fatal: $*" >&2
  exit 1
}

source "$base_dir/scripts/include/logger" \
  || fatal 'Unable to load a required library'

usage()
{
  echo "Usage: $0 name message" >&2
  exit 111
}

main()
{
  local name="$1"
  local message="$2"

  if [ -z "$name" -o -z "$message" ]; then
    usage
  fi

  print_status "$name" "$message"
}

main "$@"
exit $?

