#!/bin/sh

self="`readlink -f "$0" 2>/dev/null || realpath "$0"`"
base_dir="`dirname "$self"`/../.."

symlink_manifest()
{
  for link in \
    vm-toaster/source/medic-core/acl \
    vm-toaster/source/medic-core/ant \
    vm-toaster/source/medic-core/attr \
    vm-toaster/source/medic-core/bzip2 \
    vm-toaster/source/medic-core/couchdb \
    vm-toaster/source/medic-core/couchdb-lucene \
    vm-toaster/source/medic-core/curl \
    vm-toaster/source/medic-core/diffutils \
    vm-toaster/source/medic-core/erlang \
    vm-toaster/source/medic-core/gammu \
    vm-toaster/source/medic-core/garden-maker \
    vm-toaster/source/medic-core/icu \
    vm-toaster/source/medic-core/js \
    vm-toaster/source/medic-core/kanso \
    vm-toaster/source/medic-core/libidn \
    vm-toaster/source/medic-core/libusb \
    vm-toaster/source/medic-core/libusb-compat \
    vm-toaster/source/medic-core/libxml2 \
    vm-toaster/source/medic-core/libxslt \
    vm-toaster/source/medic-core/logrotate \
    vm-toaster/source/medic-core/lrzip \
    vm-toaster/source/medic-core/lucene \
    vm-toaster/source/medic-core/lzma \
    vm-toaster/source/medic-core/lzo \
    vm-toaster/source/medic-core/maven \
    vm-toaster/source/medic-core/ncurses \
    vm-toaster/source/medic-core/node \
    vm-toaster/source/medic-core/nodelint \
    vm-toaster/source/medic-core/nodeunit \
    vm-toaster/source/medic-core/openssh \
    vm-toaster/source/medic-core/openssl \
    vm-toaster/source/medic-core/patch \
    vm-toaster/source/medic-core/paxctl \
    vm-toaster/source/medic-core/popt \
    vm-toaster/source/medic-core/pv \
    vm-toaster/source/medic-core/readline \
    vm-toaster/source/medic-core/rsync \
    vm-toaster/source/medic-core/usb-modeswitch \
    vm-toaster/source/medic-core/usb-modeswitch-data \
    vm-toaster/source/medic-core/usbutils \
    vm-toaster/source/medic-core/xdelta \
    vm-toaster/source/medic-core/zlib \
    vm-toaster/source/vm-tools/glib \
    vm-toaster/source/vm-tools/libffi \
    vm-toaster/source/vm-tools/open-vm-tools \
    vm-toaster/source/busybox \
    vm-toaster/source/linux \
    vm-toaster/source/syslinux \
    vm-toaster/packages/java/software/java \
    java-jdk
  do echo "$link"; done
}

normalized_dirname()
{
  local rv="`dirname "$@"`" || return "$?"

  if [ "$rv" != '.' ]; then
    echo "$rv/"
  fi

  return 0
}

normalized_basename()
{
  local rv="`basename "$@"`" || return "$?"

  if [ "$rv" != '.' ]; then
    echo "$rv/"
  fi

  return 0
}

read_dirlink()
{
  local rv="`readlink "$@"`" || return "$?"

  if [ "$rv" ]; then
    echo "$rv/"
  else
    return 1
  fi

  return 0
}

upstream_directories()
{
  symlink_manifest | while read file; do
    if [ -h "$file" ]; then
      local path="`dirname "$file"`" &&
      local file="`readlink "$file"`" &&
      local base_path="`normalized_dirname "$path"`" &&
      local last_dir="`normalized_basename "$path"`" &&
      \
      # Dereference the two deepest path components
      echo "$base_path`read_dirlink "$path" || echo "$last_dir"`$file"
    else
      echo "$file"
    fi

  done

  return 0
}

main()
{
  cd "$base_dir" &&
  \
  upstream_directories \
    | tar -X - -cf - Makefile java-jdk vm-toaster \
  | xz -9ec > "vm-toaster-git-`date +%Y%m%d`.tar.xz" &&
  \
  upstream_directories \
    | tar -T - -cf - | xz -9ec \
      > "vm-toaster-upstream-`date +%Y%m%d`.tar.xz"

  return "$?"
}

main "$@"
exit "$?"

