#!/bin/bash

self="`readlink -f "$0" 2>/dev/null || realpath "$0"`"
base_dir="`dirname "$self"`/.."

fatal()
{
  echo "Fatal: $*" >&2
  exit 255
}

set_permissions()
{
  chmod 1777 platform/initrd/common/tmp &&
  chmod 0440 platform/initrd/common/etc/sudoers &&
  chmod 0750 platform/initrd/common/etc/sudoers.d

  return "$?"
}

create_empty_directories()
{
  (
    cd platform &&
    \
    for platform in x64 x86 armv6; do
      mkdir -p "images/$platform" \
        "initrd/$platform/lib" "templates/java/$platform"
    done &&
    \
    mkdir -p \
      images/x86/iso/packages \
      images/x64/iso/packages \
      images/noarch/iso/packages \
      initrd/common/etc/ashrc.d \
      initrd/common/etc/profile.d \
      initrd/common/etc/sysconfig \
      initrd/common/etc/sysconfig \
      initrd/common/dev \
      initrd/common/mnt \
      initrd/common/proc \
      initrd/common/sys \
      initrd/common/tmp \
      initrd/common/var/cache \
      initrd/common/var/empty \
      initrd/common/var/lib \
      initrd/common/var/lock \
      initrd/common/var/log \
      initrd/common/var/run \
      packages/java/storage \
      packages/java/storage/java \
      packages/vm-tools/storage \
      packages/vm-tools/storage/vm-tools \
      packages/vm-tools/storage/vm-tools/avahi/logs \
      packages/vm-tools/storage/vm-tools/avahi/state \
      packages/vm-tools/storage/vm-tools/ntpd/logs \
      packages/vm-tools/storage/vm-tools/vmtoolsd/logs \
      packages/system-services/storage \
      packages/system-services/storage/system-services \
      packages/system-services/storage/system-services/logs \
      packages/system-services/settings/system-services/cron \
      packages/medic-api/settings/medic-api \
      packages/medic-api/software/medic-api \
      packages/medic-api/storage/medic-api \
      packages/medic-core/storage/medic-core/passwd \
      packages/medic-core/storage/medic-core/nginx \
      packages/medic-core/storage/medic-core/nginx/state \
      packages/medic-core/storage/medic-core/nginx/data \
      packages/medic-core/storage/medic-core/nginx/logs \
      packages/medic-core/storage/medic-core/openssh \
      packages/medic-core/storage/medic-core/openssh/logs \
      packages/medic-core/storage/medic-core/couchdb-lucene/indexes \
      packages/medic-core/storage/medic-core/couchdb-lucene/logs \
      packages/medic-core/storage/medic-core/couchdb \
      packages/medic-core/storage/medic-core/couchdb/state \
      packages/medic-core/storage/medic-core/couchdb/data \
      packages/medic-core/storage/medic-core/couchdb/logs \
      packages/medic-core/settings/medic-core/couchdb-lucene \
      packages/medic-core/settings/medic-core/couchdb/default.d \
      packages/medic-core/settings/medic-core/couchdb/local.d \
      packages/medic-couch2pg/storage/medic-couch2pg/logs \
      packages/medic-rdbms/storage/medic-rdbms/postgresql/logs \
      packages/medic-rdbms/storage/medic-rdbms/postgresql/data \
      packages/medic-rdbms/storage/medic-rdbms/postgresql/passwd \
      packages/medic-rdbms/settings/medic-rdbms/postgresql/env \
      packages/medic-rdbms/settings/medic-rdbms/postgresql/templates/postgresql.conf.d \
      packages/medic-sentinel/settings/medic-sentinel \
      packages/medic-sentinel/software/medic-sentinel \
      packages/medic-sentinel/storage/medic-sentinel \
      packages/horticulturalist/settings/horticulturalist \
      packages/horticulturalist/software/horticulturalist \
      packages/horticulturalist/storage/horticulturalist \
      source/compiler/incoming \
      source/core/incoming \
      source/medic-core/incoming \
      source/medic-couch2pg/incoming \
      source/medic-rdbms/incoming \
      source/vm-tools/incoming
  )

  return "$?"
}


main()
{
  cd "$base_dir" \
    || fatal 'Unable to locate base directory'

  create_empty_directories \
    || fatal 'Failed to create one or more directories'
  
  set_permissions \
    || fatal 'Failed to set directory permissions'
}

main "$@"
exit "$?"

