#!/bin/sh

main()
{
  for type in 'executable' 'shared object'; do
    find . -type f | xargs file \
      | grep -F "$type" | grep ELF | cut -f1 -d: \
        | xargs strip --strip-unneeded 2>/dev/null
  done
}

main
exit "$?"

