#!/bin/sh

install()
{
  yum "$@" remove ntp &&
  yum "$@" install \
    kernel-headers kernel-devel gcc47-c++ gcc47-plugin-devel \
    autoconf automake bison flex nasm ruby patch git ntpdate \
    ncurses-devel libuuid-devel tcl expect libtool gettext-devel \
    mkisofs libattr-devel bzip2-devel perl-devel cmake
}

install "$@"
exit "$?"

