#!/bin/sh

install()
{
  yum "$@" install curl jq gperf \
    kernel-headers kernel-devel gcc48-c++ gcc48-plugin-devel autoconf \
    automake bison flex nasm ruby patch git intltool ncurses-devel \
    libuuid-devel tcl libtool gettext-devel expect mkisofs libattr-devel \
    lzma zlib-devel bzip2-devel perl-devel cmake libdb4-devel iptables-devel &&
  \
  alternatives --auto python &&
  yum "$@" install python27-boto

  return "$?"
}

install "$@"
exit "$?"

