#!/bin/bash

set -o pipefail

prefix="$1"

if ! [ -d "$prefix" ]; then
  echo "Usage: $0 <prefix>" >&2
  exit 111
fi

up='../../../../..'

(cd "$prefix" &&
  rm -rf Library usr lib/perl5 lib/engines lib/*.la \
    lib/*.a lib/*.py bin/*.py lib/python?.? lib/erlang/usr \
    lib/erlang/Install info include man share/man \
    share/gtk-doc share/doc doc logs html share/info share/emacs \
    etc/ssh_host* libexec/ssh-keysign usr/share/man etc/ssl/man) &&
\
(cd "$prefix/lib/erlang/lib" && mkdir -p .save &&
  mv asn1-* crypto-* compiler-* inets-* kernel-* os_mon-* public_key-* \
    sasl-* ssl-* stdlib-* tools-* syntax_tools-* xmerl-* .save &&
      rm -rf * && mv .save/* . && rmdir .save) &&
\
(cd "$prefix" &&
  rm -rf etc/ssh &&
    ln -sf "$up/settings/medic-core/openssh" etc/ssh &&
  rm -rf etc/nginx &&
    ln -sf "$up/settings/medic-core/nginx" etc/nginx &&
  rm -rf var/log/nginx &&
    ln -sf "$up/../storage/medic-core/nginx/logs" var/log/nginx &&
  rm -rf var/run/nginx &&
    ln -sf "$up/../storage/medic-core/nginx/state" var/run/nginx &&
  rm -rf couchdb/etc &&
    ln -sf "$up/settings/medic-core/couchdb" couchdb/etc &&
  rm -rf couchdb/log &&
    ln -sf "$up/storage/medic-core/couchdb/logs" couchdb/log &&
  rm -rf couchdb/data &&
    ln -sf "$up/storage/medic-core/couchdb/data" couchdb/data) &&
\
(cd "$prefix/lib" &&
  rm -rf erlang/erts-5.10.4/man) &&
\
(cd "$prefix/lib/node_modules" &&
  rm -rf node-gyp npm/man nodelint/man1)

