#!/bin/bash

set -o pipefail

prefix="$1"

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <prefix>" >&2
  exit 111
fi

if [ ! -d "$prefix" ]; then
  exit 0
fi

(cd "$prefix" &&
 rm -rf etc/ssh etc/nginx var/log/nginx \
   var/run/nginx couchdb/etc couchdb/log \
   couchdb/data java/logs java/conf java/indexes)

(cd "$prefix/bin" &&
  rm -f git-receive-pack git-upload-archive \
    git git-cvsserver git-shell git-upload-pack)

