#!/bin/sh

set -o pipefail

is_restart_event=''
supervise_dir="/srv/storage/system/supervisor"

_supervisor_process()
{
  local package="`basename "$1"`"
  local service="`basename "$2"`"

  local pkg_supervise_dir="$supervise_dir/$package"
  local log="$pkg_supervise_dir/logs/$service.log"

  trap '_supervisor_resync_trap "$package" "$service"' HUP
  trap '_supervisor_restart_trap "$package" "$service"' USR1
  trap '_supervisor_termination_trap "$package" "$service"' TERM

  while true; do

    rm -f "$pkg_supervise_dir/status/$package.pid" &&
    mkdir -p "$pkg_supervise_dir/status" "$pkg_supervise_dir/logs"

    # Is service down?
    #   If so, block on the FIFO; a write is our signal to resume.
    
    local svc_down_fifo="$pkg_supervise_dir/status/$service.down"
    
    if [ -p "$svc_down_fifo" ]; then
      read < "$svc_down_fifo" &>/dev/null
      rm -f "$svc_down_fifo"
    fi
    
    # Fork-and-exec:
    #  This attempts to start the supervised process.
        
    (exec "/srv/scripts/$package/run/$service" >> "$log" 2>&1) &

    local pid="$!"
    local pid_file="$pkg_supervise_dir/status/$service.pid"
    
    echo "$pid" > "$pid_file" &&
    wait "$pid" &&
    rm -f "$pid_file"

    local status="$?"
    
    if [ "$status" -eq 0 ]; then
      echo "`date`: Service '$service' in package '$package'" \
        "exited normally (pid was '$pid')" >> "$log"
    else
      echo "`date`: Service '$service' in package '$package'" \
        "exited with non-zero status $status (pid was '$pid')" >> "$log"

      if [ "$is_restart_event" ]; then
        is_restart_event=''
      else
        sleep 5
      fi
    fi

    echo "`date`: Restarting service '$service' in '$package'" >> "$log"
  done
}

_supervisor_termination_trap()
{
  local package="$1"
  local service="$2"

  _supervisor_terminate_service "$package" "$service"
  exit 111
}

_supervisor_restart_trap()
{
  local package="$1"
  local service="$2"

  is_restart_event='true'
  _supervisor_terminate_service "$package" "$service"
}

_supervisor_resync_trap()
{
  local package="$1"
  local service="$2"

  local pkg_supervise_dir="$supervise_dir/$package"
  local svc_down_fifo="$pkg_supervise_dir/status/$service.down"

  if supervisor_is_service_running "$package" "$service"; then
    if [ -p "$svc_down_fifo" ]; then
      _supervisor_terminate_service "$package" "$service"
    fi
  fi
  
  return 0
}

_start_supervisor_process()
{
  local package="$1"
  local service="$2"

  local ppid_dir="$supervise_dir/$package/status"
  local ppid_file="$ppid_dir/$service.ppid"

  supervisor_service_exists "$package" "$service" || return 1

  if supervisor_is_service_watched "$package" "$service"; then
    return 2
  fi
    
  trap '_terminate_supervisor_process "$package" "$service"' TERM

  _supervisor_process "$package" "$service" &>/dev/null &

  local pid="$!"
  mkdir -p "$ppid_dir" &&
  echo "$pid" > "$ppid_file"
  
  return "$?"
}

_terminate_supervisor_process()
{
  local package="$1"
  local service="$2"
  
  supervisor_service_exists "$package" "$service" || return 1

  local pkg_status_dir="$supervise_dir/$package/status"
  local ppid_file="$pkg_status_dir/$service.ppid"
  
  if ! supervisor_is_service_watched "$package" "$service"; then
    return 2
  fi
  
  local ppid="`cat "$ppid_file" 2>/dev/null`"

  if ! [ "$ppid" ]; then
    return 3
  fi

  rm -f "$ppid_file" "$pkg_status_dir/$service.down" &&
  kill -TERM "$ppid" 2>/dev/null
  
  return "$?"
}

_pidfile_has_active_process()
{
  local pid_file="$1"
  
  if ! [ -f "$pid_file" ]; then
    return 1
  fi

  local pid="`cat "$pid_file" 2>/dev/null`"

  if ! [ "$pid" ]; then
    return 2
  fi

  if ! [ -d "/proc/$pid" ]; then
    return 3
  fi

  return 0
}

_supervisor_terminate_service()
{
  local package="$1"
  local service="$2"

  local pkg_status_dir="$supervise_dir/$package/status"
  local pid_file="$pkg_status_dir/$service.pid"

  local pid="`cat "$pid_file" 2>/dev/null`"

  if [ "$pid" ]; then
    rm -f "$pid_file" &&
    kill -TERM "$pid" 2>/dev/null
  fi
}

_supervisor_apply()
{
  local operation="$1"
  local function="$2"
  local package="`basename "$3"`"
  shift 3
  
  local rv='0'
  local services="$@"

  if ! [ -d "/srv/scripts/$package" ]; then
    warn "Unable to locate package '$package'"
    return 255
  fi

  supervisor_package_exists "$package" || return 255

  if [ "$#" -le 0 ]; then
    services="/srv/scripts/$package/run"/*
  fi

  for service in $services; do
  
    local service="`basename "$service"`"

    if [ "$#" -le 0 -a "$service" = '*' ]; then
      warn "Unable to locate any services for package '$package'"
      return 255
    fi

    supervisor_service_exists "$package" "$service" || return 255

    if supervisor_is_service_disabled "$package" "$service"; then
      continue
    fi

    "$function" "$package" "$service"
      
    if [ "$?" -ne 0 ]; then
      rv="$(($rv + 1))"
      warn "Failed to $operation supervisor for '$package/$service'"
    fi
  done

  return "$rv"
}

supervisor_start()
{
  _supervisor_apply 'start' _start_supervisor_process "$@"
  return "$?"
}

supervisor_stop()
{
  _supervisor_apply 'stop' _terminate_supervisor_process "$@"
  return "$?"
}

supervisor_reset()
{
  if [ -d "$supervise_dir" ]; then
    find "$supervise_dir" \( -type p -a -name '*.down' \) \
	-o -name '*.pid' -o -name '*.ppid' -exec rm -f {} \;
  fi

  return 0
}

supervisor_service_disable()
{
  local package="`basename "$1"`"
  local service="`basename "$2"`"

  supervisor_service_exists "$package" "$service" || return 1
    
  if supervisor_is_service_disabled "$package" "$service"; then
    warn "Service '$package/$service' is already disabled"
    return 2
  fi

  if supervisor_is_service_watched "$package" "$service"; then
    if ! supervisor_stop "$package" "$service"; then
      warn "Failed to stop supervisor for '$package/$service'"
      return 3
    fi
  fi
  
  touch "$supervise_dir/$package/status/$service.disabled"
  return 0
}

supervisor_service_enable()
{
  local package="`basename "$1"`"
  local service="`basename "$2"`"

  supervisor_service_exists "$package" "$service" || return 1

  if ! supervisor_is_service_disabled "$package" "$service"; then
    warn "Service '$package/$service' is not currently disabled"
    return 2
  fi

  rm -f "$supervise_dir/$package/status/$service.disabled"

  if ! supervisor_start "$package" "$service"; then
    warn "Failed to start supervisor for '$package/$service'"
    return 3
  fi

  return 0
}

supervisor_service_down()
{
  local package="`basename "$1"`"
  local service="`basename "$2"`"

  supervisor_service_exists "$package" "$service" || return 1

  if ! supervisor_is_service_watched "$package" "$service"; then
    warn "Supervisor is not running for '$package/$service'"
    return 2
  fi
  
  if supervisor_is_service_down "$package" "$service"; then
    warn "Service '$package/$service' is already down"
    return 3
  fi

  local pkg_supervise_dir="$supervise_dir/$package"
  local ppid="`cat "$pkg_supervise_dir/status/$service.ppid"`"
  local svc_down_fifo="$pkg_supervise_dir/status/$service.down"
  
  rm -f "$svc_down_fifo" && mkfifo -m 0600 "$svc_down_fifo" &&
  kill -HUP "$ppid" 2>/dev/null
  
  if [ "$?" -ne 0 ]; then
    return 4 # FIFO / signal failure
  fi
    
  return 0
}

supervisor_service_up()
{
  local package="`basename "$1"`"
  local service="`basename "$2"`"

  supervisor_service_exists "$package" "$service" || return 1

  if supervisor_is_service_disabled "$package" "$service"; then
    warn "Service '$package/$service' is currently disabled"
    return 2
  fi

  if ! supervisor_is_service_watched "$package" "$service"; then
    warn "Supervisor is not running for '$package/$service'"
    return 3
  fi

  if ! supervisor_is_service_down "$package" "$service"; then
    warn "Service '$package/$service' is already running"
    return 4
  fi

  # Write to the FIFO:
  #   This unblocks `_supervisor_process` and starts the service.
  
  local pkg_supervise_dir="$supervise_dir/$package"
  local svc_down_fifo="$pkg_supervise_dir/status/$service.down"

  echo '1' > "$svc_down_fifo" || return 5
  return 0
}

supervisor_service_restart()
{
  local package="`basename "$1"`"
  local service="`basename "$2"`"

  supervisor_service_exists "$package" "$service" || return 1

  if supervisor_is_service_disabled "$package" "$service"; then
    warn "Service '$package/$service' is currently disabled"
    return 2
  fi

  if ! supervisor_is_service_watched "$package" "$service"; then
    warn "Supervisor is not running for '$package/$service'"
    return 3
  fi
  
  if supervisor_is_service_down "$package" "$service"; then
    warn "Service '$package/$service' is down"
    return 4
  fi

  if ! supervisor_is_service_running "$package" "$service"; then
    warn "Service '$package/$service' is not currently running"
    return 5
  fi

  local pkg_supervise_dir="$supervise_dir/$package"
  local ppid="`cat "$pkg_supervise_dir/status/$service.ppid"`"

  kill -USR1 "$ppid" 2>/dev/null

  if [ "$?" -ne 0 ]; then
    return 6 # Signal failure
  fi

  return 0
}

supervisor_service_reload()
{
  local package="`basename "$1"`"
  local service="$2"

  supervisor_service_exists "$package" "$service" || return 1

  if ! supervisor_is_service_running "$package" "$service"; then
    warn "Service '$package/$service' is not currently running"
    return 2
  fi

  local pkg_supervise_dir="$supervise_dir/$package"
  local pid="`cat "$pkg_supervise_dir/status/$service.pid"`"

  kill -HUP "$pid" 2>/dev/null

  if [ "$?" -ne 0 ]; then
    return 3 # Signal failure
  fi

  return 0
}

supervisor_list_all_packages()
{
  for package in "/srv/scripts"/*; do
    package="`basename "$package"`"
    if [ "$package" != '*' -a "$package" != 'system' ]; then
      echo "$package"
    fi
  done
  
  return 0
}

supervisor_list_all_services()
{
  local package="`basename "$1"`"

  for service in "/srv/scripts/$package/run"/*; do
    service="`basename "$service"`"
    if [ "$service" != '*' ]; then
      echo "$service"
    fi
  done

  return 0
}

supervisor_list_services_filtered()
{
  local package="`basename "$1"`"
  shift 1
  
  supervisor_list_all_services "$package" | while read service; do
    if "$@" "$package" "$service"; then
      echo "$service"
    fi
  done

  return 0
}

supervisor_list_expected_services()
{
  local package="`basename "$1"`"

  supervisor_list_services_filtered \
    "$package" supervisor_is_service_expected
}

supervisor_list_unexpected_services()
{
  local package="`basename "$1"`"

  supervisor_list_services_filtered \
    "$package" ! supervisor_is_service_expected
}


supervisor_list_down_services()
{
  local package="`basename "$1"`"
  
  supervisor_list_services_filtered \
    "$package" supervisor_is_service_down
}

supervisor_list_watched_services()
{
  local package="`basename "$1"`"

  # List services where supervisor is running:
  #   Loop over control data to avoid iterating through everything.
  
  for service in "$supervise_dir/$package/status"/*.ppid; do
    service="`basename "$service" .ppid`"
    if [ "$service" != '*' ]; then
      if supervisor_is_service_watched "$package" "$service"; then
        echo "$service"
      fi
    fi
  done

  return 0
}

supervisor_list_running_services()
{
  local package="`basename "$1"`"

  # List services where intended process is running:
  #   Loop over control data to avoid iterating through everything.
  
  for service in "$supervise_dir/$package/status"/*.pid; do
    service="`basename "$service" .pid`"
    if [ "$service" != '*' ]; then
      if supervisor_is_service_running "$package" "$service"; then
      	echo "$service"
      fi
    fi
  done

  return 0
}

supervisor_is_service_disabled()
{
  local package="`basename "$1"`"
  local service="`basename "$2"`"
  
  [ -f "$supervise_dir/$package/status/$service.disabled" ]
}

supervisor_is_service_watched()
{
  local package="`basename "$1"`"
  local service="`basename "$2"`"
  
  _pidfile_has_active_process \
    "$supervise_dir/$package/status/$service.ppid"
}

supervisor_is_service_running()
{
  local package="`basename "$1"`"
  local service="`basename "$2"`"

  _pidfile_has_active_process \
    "$supervise_dir/$package/status/$service.pid"
}

supervisor_is_service_down()
{
  local package="`basename "$1"`"
  local service="`basename "$2"`"

  [ -p "$supervise_dir/$package/status/$service.down" ]
}

supervisor_is_service_expected()
{
  supervisor_service_exists "$@" || return 1
  supervisor_is_service_down "$@" && return 2
  supervisor_is_service_disabled "$@" && return 3

  return 0
}

supervisor_package_exists()
{
  local package="`basename "$1"`"

  if ! [ -d "/srv/scripts/$package" ]; then
    warn "Package '$package' does not exist"
    return 1
  fi

  return 0
}

supervisor_service_exists()
{
  local package="`basename "$1"`"
  local service="`basename "$2"`"

  if ! [ -x "/srv/scripts/$package/run/$service" ]; then
    warn "Service '$package/$service' does not exist"
    return 1
  fi

  return 0
}
