#!/bin/bash

log()
{
  logger "$1" "$platform"
}

disable_parallelism()
{
  export MAKE="`echo "$MAKE" | sed 's/--\?j\(obs\)\? *[0-9]\+//g;'`"
}

disable_stack_protector()
{
  local regex='s/ *-fstack-protector[A-Za-z0-9-]*//g;'

  export CFLAGS="`echo "$CFLAGS" | sed "$regex"`"
  export CXXFLAGS="`echo "$CFLAGS" | sed "$regex"`"
}

disable_stack_protector_strong()
{
  local regex='s/ *-fstack-protector-strong[A-Za-z0-9-]*//g;'

  export CFLAGS="`echo "$CFLAGS" | sed "$regex"`"
  export CXXFLAGS="`echo "$CFLAGS" | sed "$regex"`"
}

weaken_fortify_source()
{
  local regex='s/ *-D_FORTIFY_SOURCE=2/ -D_FORTIFY_SOURCE=1/g;'

  export CFLAGS="`echo "$CFLAGS" | sed "$regex"`"
  export CXXFLAGS="`echo "$CFLAGS" | sed "$regex"`"
}

disable_fortify_source()
{
  local regex='s/ *-D_FORTIFY_SOURCE=[0-2]*//g;'

  export CFLAGS="`echo "$CFLAGS" | sed "$regex"`"
  export CXXFLAGS="`echo "$CFLAGS" | sed "$regex"`"
}

simple_cflags()
{
  export CFLAGS="$CFLAGS_SIMPLE"
  export CXXFLAGS="$CFLAGS_SIMPLE"
}

simple_ldflags()
{
  export LDFLAGS="$LDFLAGS_SIMPLE"
}

disable_cppflags()
{
  unset CPPFLAGS
}

disable_library_path()
{
  unset LD_LIBRARY_PATH
  unset DYLD_LIBRARY_PATH

  export LD_LIBRARY_PATH="$INITIAL_LD_LIBRARY_PATH"
  export DYLD_LIBRARY_PATH="$INITIAL_DYLD_LIBRARY_PATH"
}

remove_cppflags_from_cflags()
{
  export CFLAGS="$CFLAGS_SIMPLE $CFLAGS_INCLUDE"
  export CXXFLAGS="$CFLAGS"
}

prepend_path()
{
  for dir in "$@"; do
    local bin="$dir/bin"
    local lib="$dir/lib"
    local pkg="$dir/lib/pkgconfig"
    export PATH="$bin${PATH:+:}$PATH"
    export PKG_CONFIG_PATH="$pkg${PKG_CONFIG_PATH:+:}$PKG_CONFIG_PATH"
    export LD_LIBRARY_PATH="$lib${LD_LIBRARY_PATH:+:}$LD_LIBRARY_PATH"
    export DYLD_LIBRARY_PATH="$lib${DYLD_LIBRARY_PATH:+:}$DYLD_LIBRARY_PATH"
  done
}

append_path()
{
  for dir in "$@"; do
    local bin="$dir/bin"
    local lib="$dir/lib"
    local pkg="$dir/lib/pkgconfig"
    export PATH="$PATH${PATH:+:}$bin"
    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH${PKG_CONFIG_PATH:+:}$pkg"
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH${LD_LIBRARY_PATH:+:}$lib"
    export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH${DYLD_LIBRARY_PATH:+:}$lib"
  done
}

build_version()
{
  local name="$1"
  local cut_fields="$2"

  if [ -z "$cut_fields" ]; then
    cut_fields='-9'
  fi

  readlink "$name" | cut -d- -f2- \
    | sed 's/^v//;' | cut -d. -f"$cut_fields"
}

build_autoconf()
{
  local name="$1"
  local configure_args="$2"
  local make_args="$3"
  local make_install_args="$4"

  builder_should_run "$name" || return 0

  (cd "$name" \
    && sh -c "./configure $configure_args" \
    && sh -c "$MAKE $make_args" \
    && sh -c "$MAKE install $make_install_args") 2>&1 | log "$name"

  builder_check_status "$name" "${PIPESTATUS[0]}"
}

build_config()
{
  local name="$1"
  local config_args="$2"
  local make_args="$3"
  local make_install_args="$4"

  builder_should_run "$name" || return 0

  (cd "$name" \
    && echo "./Configure $config_args $CFLAGS $build_platform" \
    && sh -c "./Configure $config_args $CFLAGS $build_platform" \
    && sh -c "$MAKE $make_args" \
    && sh -c "$MAKE install $make_install_args") 2>&1 | log "$name"
  
  builder_check_status "$name" "${PIPESTATUS[0]}"
}

builder_normalize_platform()
{
  local platform="$1"

  if [[ "$platform" = x86_64* ]]; then
    rv='x64'
  elif [[ "$platform" = x86* ]]; then
    rv='x86'
  elif [[ "$platform" = i?86 ]]; then
    rv='x86'
  else
    rv='x86'
  fi

  echo "$rv"
}

builder_platform_to_architecture()
{
  local platform="$1"
  local bits="$2"

  local rv=''

  if [ -z "$platform" ]; then
    platform="`uname -m`"
  fi

  if [[ "$platform" = x86_64* ]]; then
    rv='intel'
  elif [[ "$platform" = x64* ]]; then
    rv='intel'
  elif [[ "$platform" = x86* ]]; then
    rv='intel'
  elif [[ "$platform" = i?86 ]]; then
    rv='intel'
  elif [[ "$platform" = armv6* ]]; then
    rv='armv6'
  elif [ "$platform" = 'unknown' ]; then
    rv='intel'
  fi

  echo "$rv"
}

builder_platform_to_bits()
{
  local platform="$1"
  local bits="$2"

  if [[ "$platform" = x86_64* ]]; then
    bits='64'
  elif [[ "$platform" = x64* ]]; then
    bits='64'
  elif [[ "$platform" = x86* ]]; then
    bits='32'
  elif [[ "$platform" = i?86 ]]; then
    bits='32'
  elif [[ "$platform" = armv6* ]]; then
    bits='32'
  fi

  echo "$bits"
}


builder_fix_erlang_dso_linkage()
{
  local bits="$1"
  local name='fix-erlang-dso-linkage'

  builder_should_run "$name" || return 0

  (cd 'erlang' && erl_top="`pwd`" &&
   for dir in wx crypto asn1 runtime_tools; do
     (cd "lib/$dir/c_src" &&
       $MAKE clean opt ERL_TOP="$erl_top" LD="gcc -m$bits")
   done && $MAKE install) 2>&1 | log "$name"
  
   builder_check_status "$name" "${PIPESTATUS[0]}"
}

builder_remove_static_libraries()
{
  while [ "$#" -gt 0 ]; do
    local library_name="$1"
    shift 1
    rm -f "$prefix/lib/lib$library_name.a"
  done
}

builder_install_file()
{
  local name="$1"
  local source_path="$2"
  local target_path="$3"
  local target_directory="$target_path"

  builder_should_run "$name" || return 0

  if ! [ -d "$target_directory" ]; then
    target_directory="`dirname "$target_directory"`"
  fi

  mkdir -p "$target_directory" &&
  cp -a "$source_path" "$target_path"
  
  builder_check_status "$name" "$?"
}

build_make()
{
  local name="$1"
  local target="$2"
  local make_args="$3"
  local include_flags="$4"

  builder_should_run "$name" || return 0

  if [ "$include_flags" ]; then
    make_args="$make_args CFLAGS=\"$CFLAGS\" LDFLAGS=\"$LDFLAGS\""
  fi

  (cd "$name" \
    && sh -c "$MAKE $target $make_args") 2>&1 | log "$name"
   
  builder_check_status "$name" "${PIPESTATUS[0]}"
}

build_make_install()
{
  local name="$1"
  local prefix="$2"
  local make_args="$3"

  builder_should_run "$name" || return 0

  (cd "$name" \
    && sh -c "$MAKE $make_args CFLAGS=\"$CFLAGS\" LDFLAGS=\"$LDFLAGS\"" \
    && sh -c "$MAKE install $make_args PREFIX=\"$prefix\"") 2>&1 | log "$name"
  
  builder_check_status "$name" "${PIPESTATUS[0]}"
}

build_npm_local()
{
  local name="$1"
  local prefix="$2"

  builder_should_run "$name" || return 0

  (cd "$name" && unset MAKE &&
    "$prefix/bin/npm" install -g) 2>&1 | log "$name"
  
  builder_check_status "$name" "${PIPESTATUS[0]}"
}

build_npm_remote()
{
  local name="$1"
  local prefix="$2"

  builder_should_run "$name" || return 0
  ("$prefix/bin/npm" install "$name" -g) 2>&1 | log "$name"
  
  builder_check_status "$name" "${PIPESTATUS[0]}"
}

build_ant()
{
  local name="$1"
  local prefix="$2"

  builder_should_run "$name" || return 0

  (cd "$name" &&
    sh ./build.sh -Ddist.dir="$prefix/java" dist) 2>&1 | log "$name"
  
  builder_check_status "$name" "${PIPESTATUS[0]}"
}

build_maven()
{
  local name="$1"
  local prefix="$2"

  builder_should_run "$name" || return 0

  (cd "$name" &&
    yes 'yes' | M2_HOME="$prefix/java" \
        "$prefix/java/bin/ant") 2>&1 | log "$name"
  
  builder_check_status "$name" "${PIPESTATUS[0]}"
}

build_lucene()
{
  local name="$1"
  local prefix="$2"

  builder_should_run "$name" || return 0

  (cd "$name" &&
    "$prefix/java/bin/ant" ivy-bootstrap \
        -Divy_install_path="$prefix/java/lib" &&
    "$prefix/java/bin/ant" compile jar \
        -lib "$prefix/java/lib" &&
    cp build/core/*.jar "$prefix/java/lib") 2>&1 | log "$name"
  
  builder_check_status "$name" "${PIPESTATUS[0]}"
}

build_couchdb_lucene()
{
  local name="$1"
  local prefix="$2"

  builder_should_run "$name" || return 0

  (cd "$name" &&
    "$prefix/java/bin/mvn" && mkdir -p 'target/output' && (
	cd 'target/output' && for i in ../couchdb-lucene-*.tar.gz; do
            tar xvzf "$i" && cp -Rv couchdb-lucene-*/* "$prefix/java";
        done
    ); rm -rf 'target/output') 2>&1 | log "$name"
  
  builder_check_status "$name" "${PIPESTATUS[0]}"
}

build_bzip2()
{
  local name="$1"
  local prefix="$2"

  builder_should_run "$name" || return 0

  ( (cd "$name" &&
     make -f Makefile-libbz2_so &&
     make install PREFIX="$prefix" &&
     cp -P libbz2.so.* "$prefix/lib") &&
    \
    (cd "$prefix/lib" &&
     ln -sf libbz2.so.1.0 libbz2.so.1) ) 2>&1 | log "$name" 
}

build_cmake()
{
  local name="$1"
  local prefix="$2"
  local cmake_args="$3"

  builder_should_run "$name" || return 0
  cmake_args="-DCMAKE_INSTALL_PREFIX="$prefix" $cmake_args"

  (cd "$name" && cmake $cmake_args &&
    make && make install) 2>&1 | log "$name"
}

build_rebar()
{
  local name="$1"
  local prefix="$2"
  local command="$3"
  local final_binary="$4"

  builder_should_run "$name" || return 0

  if [ -z "$command" ]; then
    command="make"
  fi

  if [ -z "$final_binary" ]; then
    final_binary="$name"
  fi

  (cd "$name" && "$command" &&
    chmod +x "$final_binary" &&
    mv "$final_binary" "$prefix/bin") 2>&1 | log "$name"
}

builder_clean_target()
{
  local name="$1"
  local prefix="$2"

  builder_should_run "$name" || return 0

  ( (cd "$prefix" &&
     rm -rf Library) &&
    \
    (cd "$prefix/java" &&
      rm -f LICENSE* NOTICE* README* \
        INSTALL* KEYS* WHATSNEW* *.xml) &&
    \
    (cd "$prefix/java/bin" &&
      rm -f runant.p? *.bat *.cmd m2.conf) &&
    \
    (cd "$prefix/lib/erlang/lib" &&
      rm -rf megaco-* wx-* hipe-*) ) 2>&1 | log "$name"
}

fix_libtool()
{
  for dir in "$@"; do
    (cd "$dir" &&
      libtoolize --automake --copy &&
      aclocal -I config && autoheader &&
      automake --add-missing --copy && autoconf) 2>/dev/null \
	|| fatal "Unable to regenerate libtool files for '$dir'"
  done

  return 0
}

builder_initialize()
{
  last_pkg_file="`mktemp`"
  run_status_file="`mktemp`"
  last_version_file="`mktemp`"

  trap builder_cleanup EXIT
}

builder_check_status()
{
  local name="$1"
  local pipe_status="$2"

  if [ "$pipe_status" -ne 0 ]; then
    echo >&2
    echo "A failure occurred while building '$name':" >&2
    echo "  Subprocess exited with a status code of $pipe_status." >&2
    echo "  Please check the source tree for problems and retry." >&2
    echo >&2
    exit "$pipe_status"
  fi

  true
}

builder_cleanup()
{
  rm -f "$run_status_file" "$last_pkg_file" "$last_version_file"
}

builder_should_run()
{
  local pkg="`echo "$1" | sed 's/\//-/g;'`"
  local version="$2"

  local run_status="`cat "$run_status_file"`"

  local last_pkg="`cat "$last_pkg_file"`"
  local last_version="`cat "$last_version_file"`"

  # Package may have multiple build steps:
  #   If we've already seen the name of the package we're supposed
  #   to stop on, continue executing steps until the name changes.

  if [ "$run_status" -lt 0 ]; then
    if [ "$pkg $version" != "$last_pkg $last_version" ]; then
      run_status='1' # State: stopped
      echo -n "$run_status" > "$run_status_file"
    fi
    return "$run_status"
  fi

  # Check for start, stop:
  #   This lets you specify inclusive ranges of packages to build.

  if [ "$run_status" -eq 0 ]; then
    if [ "$pkg_stop" -a "$last_pkg $last_version" = "$pkg_stop $pkg_stop_version" ]; then
      if [ "$pkg $version" != "$last_pkg $last_version" ]; then
        run_status='1' # State: stopped
      else
        run_status='-1' # State: stopping
      fi
      echo -n "$run_status" > "$run_status_file"
    fi
  else
    if [ "$pkg_start" -a "$pkg $version" = "$pkg_start $pkg_start_version" ]; then
      run_status='0' # State: running
      echo -n "$run_status" > "$run_status_file"
    fi
  fi;

  echo -n "$pkg" > "$last_pkg_file"
  echo -n "$version" > "$last_version_file"

  [ "$run_status" -le 0 ]
  return "$?"
}

builder_move_libraries()
{
  local name="$1"
  local prefix="$2"
  local dir="$3"

  builder_should_run "$name" || return 0

  (cd "$prefix" &&
    if [ -d "$dir" ]; then \
        mv "$dir"/* lib/ && rmdir "$dir"; fi) 2>&1 | log "$name"
}

builder_setup_environment()
{
  prefix="$1"
  pkg_start="$2"
  pkg_start_version="$3"
  pkg_stop="$4"
  pkg_stop_version="$5"
  uname="$6"
  architecture="$7"
  bits="$8"
  parallel="$9"

  timestamp="`date +%Y%m%d-%H%M%S`"

  if [ "$pkg_start" ]; then
    echo -n 1 > "$run_status_file"
  else
    echo -n 0 > "$run_status_file"
  fi

  unset PLATFORM

  export CC='gcc'
  export CXX='g++'
  export MAKE='gmake'
  export GNUMAKE='gmake'

  export INITIAL_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
  export INITIAL_DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH"

  prepend_path "$prefix"

  builder_detect_system \
    || fatal 'Unsupported system; please edit Makefile'

  if [ "$bits" -eq 64 ]; then
    (cd "$prefix" && rm -rf lib64 && mkdir -p lib && ln -s lib lib64) \
      || fatal 'Failed to create symbolic link for 64-bit libraries'
  fi

  if [ "$parallel" ]; then
    export MAKE="$MAKE -j$parallel"
  fi

  if [ "$uname" = 'Darwin' -a "$architecture" = 'intel' -a "$bits" -eq 32 ]; then
    export LDFLAGS_SIMPLE="-arch i386"
  fi

  export CPPFLAGS_SIMPLE="-D_FORTIFY_SOURCE=2"
  export CFLAGS_SIMPLE="-Os -fstack-protector-strong"
  export CFLAGS_INCLUDE="-I$prefix/include -L$prefix/lib"

  if [ "$architecture" = 'intel' ]; then
    export CFLAGS_SIMPLE="$CFLAGS_SIMPLE -m$bits -mtune=i686"
  elif [[ "$architecture" = armv6* ]]; then
    local cflags_arch="-march=armv6 -mfpu=vfp -mfloat-abi=hard"
    export CFLAGS_SIMPLE="$CFLAGS_SIMPLE $cflags_arch"
  fi

  export CPPFLAGS="$CPPFLAGS_SIMPLE"
  export LDFLAGS="$LDFLAGS_SIMPLE -L$prefix/lib"
  export CFLAGS="$CFLAGS_SIMPLE $CFLAGS_INCLUDE $CPPFLAGS"
  export CXXFLAGS="$CFLAGS"
}

builder_detect_system()
{
  # Ensure `uname` is set
  if [ -z "$uname" ]; then
    uname="`uname -s`"
  fi

  # Ensure `platform` is set
  if [ -z "$platform" ]; then
    local machine="`uname -m`"
    platform="`builder_normalize_platform "$machine"`"
  fi

  # Guess machine word size if necessary
  if [ -z "$bits" ]; then
    if [ "`echo "$platform" | grep 64$`" ]; then
      bits='64'
    else
      bits='32'
    fi
  fi

  # Ensure architecture is set
  if [ -z "$architecture" ]; then
    architecture="`builder_platform_to_architecture "$platform"`"
  fi

  # Detect architecture/platform
  if [ "$architecture" = 'intel' ]; then
    if [ "$uname" = 'Darwin' ]; then
        if [ "$bits" -eq 64 ]; then
          build_cpu='x64'
          build_platform="darwin64-x86_64-cc"
          build_arch="x86_64-apple-darwin10.0.0"
          build_extra_options="--enable-darwin-64bit"
        else
          build_cpu='ia32'
          build_platform="darwin-i386-cc"
          build_arch="i386-apple-darwin10.0.0"
          build_extra_options="--enable-darwin-32bit"
        fi
    elif [ "$uname" = 'Linux' ]; then
       if [ "$bits" -eq 64 ]; then
          build_cpu='x64'
          build_platform="linux-elf"
          build_arch="x86_64-linux-gnu"
        else
          build_cpu='ia32'
          build_platform="linux-elf"
          build_arch="i586-linux-gnu"
        fi
    fi
  elif [[ "$architecture" = armv6* ]]; then
    build_cpu='arm'
    build_platform="linux-armv4"
    build_arch="arm-linux-gnueabihf"
  fi

  if [ -z "$build_cpu" -o -z "$build_arch" -o -z "$build_platform" ]; then
    echo 'Warning: Unrecognized or unsupported architecture' >&2
    return 1
  fi

  return 0
}


