#!/bin/sh

install()
{
  apt-get "$@" install curl jq bc python-boto gperf ec2-api-tools g++ \
    cloud-utils linux-headers-generic linux-libc-dev gcc-5-plugin-dev \
    autoconf automake bison flex nasm ruby patch git intltool pkg-config \
    libncurses5-dev libreadline6-dev libpopt-dev libpcre3-dev uuid-dev \
    expect tcl libtool libgettextpo-dev libattr1-dev zlib1g-dev libbz2-dev \
    libicu-dev libperl-dev cmake libdb5.3-dev iptables-dev zip ccache gawk &&
  \
  # Use python-boto's s3put by default
  zcat /usr/share/doc/python-boto/examples/s3put.gz > /usr/bin/s3put &&
  chmod +x /usr/bin/s3put

  return "$?"
}

install "$@"
exit "$?"

