#!/bin/sh

install()
{
  apt-get "$@" install curl jq bc \
    linux-headers-generic linux-libc-dev g++ gcc-5-plugin-dev \
    autoconf automake bison flex nasm ruby patch git ntpdate intltool \
    pkg-config libncurses5-dev uuid-dev expect tcl libtool gettext \
    libgettextpo-dev genisoimage libattr1-dev zlib1g-dev libbz2-dev \
    libperl-dev cmake libdb5.3-dev iptables-dev zip gperf ccache

  return "$?"
}

install "$@"
exit "$?"

