#!/bin/bash

set -o pipefail

self="`readlink -f "$0" 2>/dev/null || realpath "$0"`"
base_dir="`dirname "$self"`/../.."

fatal() {

  echo "Fatal: $@" >&2
  exit 111
}

usage() {

  local app="`basename "$0"`"
  local args='[ settings_path platform instance_type build_options ]'

  echo "Usage: $app $args" >&2
  exit 1
}

discover_server_role() {

  curl -s 'http://169.254.169.254/latest/meta-data/iam/info' \
    | jq .InstanceProfileArn | sed -r 's/^"[^\/]*\/([^"]+)"$/\1/;' 2>/dev/null
}

ssh_command() {

  local host="$1"
  local identity="$2"
  local remote_command="$3"

  local ssh_options='-q -o StrictHostKeyChecking=no -o RequestTTY=yes'

  if [ -z "$identity" ]; then
    ssh $ssh_options "$host" "$remote_command"
  else
    ssh $ssh_options -i "$identity" "$host" "$remote_command"
  fi

  return "$?"
}

main() {

  local settings="$1"
  local platform="$2"
  local instance_type="$3"
  local build_options="$4"

  local fs_size='20'
  local iam_role='$inherit'
  local time_zone='America/Los_Angeles'

  local security_group='ssh-only'
  local default_region='us-west-2'
  local default_availability_zone='us-west-2a'
  local ssh_key_name='nightly-builds@medicmobile.org'

  local vm_url='https://github.com/medic/medic-os'
  local s3_base_url='https://medic.s3.amazonaws.com'

  local source_url="$s3_base_url/os/source"
  local mirror_url="$s3_base_url/os/mirror"

  if [ "$1" = '-h' -o "$1" = '--help' -o $# -gt 4 ]; then
    usage
  fi

  if [ -z "$platform" ]; then
    platform='x64'
  fi

  if [ -z "$instance_type" ]; then
    if [ "$platform" = 'x86' ]; then
      instance_type='c1.medium'
    else
      instance_type='c3.2xlarge'
    fi
  fi

  settings="`aws_load_settings "$settings"`" &&
    eval "$settings" && aws_cleanup_environment \
      || fatal 'Unable to read AWS environment/settings file'

  local ami='';
  local flavor_name='';
  local flavor_user='';
  local flavor_update_command='';
  local ssh_private_key_path='';
  local ssh_private_key_contents='';

  local flavor='debian';

  case "$flavor" in
    debian)
      flavor_user='ubuntu'
      flavor_name='Ubuntu Linux'
      flavor_update_command='apt-get -qy update'
      flavor_upgrade_command='apt-get -qy upgrade'
    ;;
    redhat)
      flavor_user='ec2-user'
      flavor_name='Amazon Linux'
      flavor_update_command='true'
      flavor_upgrade_command='yum -qy update'
    ;;
  esac

  case "$flavor" in
    debian)
      case "$platform" in
        x64)
          ami='ami-0a00ce72' ;;
        x86)
          ami='ami-49f43f31' ;;
      esac
    ;;
    redhat)
      case "$platform" in
        x64)
          ami='ami-eff1028f' ;;
        x86)
          ami='ami-cffea7ff' ;;
      esac
    ;;
  esac

  if [ "$time_zone" ]; then
    export TZ="$time_zone"
  fi

  if [ "$SSH_PRIVATE_KEY" ]; then
    ssh_private_key_path="$SSH_PRIVATE_KEY"
    ssh_private_key_contents="`cat "$ssh_private_key_path"`" \
      || fatal "Couldn't read private key from '$ssh_private_key_path'"
  fi

  if ! [ -f "$ssh_private_key_path" ]; then
    fatal "SSH private key file '$ssh_private_key_path' not found"
  fi

  if [ -z "$EC2_REGION" ]; then
    EC2_REGION="$default_region"
  fi

  if [ -z "$EC2_AVAILABILITY_ZONE" ]; then
    EC2_AVAILABILITY_ZONE="$default_availability_zone"
  fi

  local extra_create_args=''

  if [ "$iam_role" = '$inherit' ]; then
    extra_create_args="-p \"`discover_server_role`\"" \
      || fatal 'Unable to discover server role'
  else
    extra_create_args="-p '$iam_role'"
  fi

  local n='16'
  local tab="`printf '\t'`"

  echo -n 'Creating instance... ' >&2

  local instance_data="`
    ec2-run-instances "$ami" $extra_create_args \
      -g "$security_group" -k "$ssh_key_name" \
      -t "$instance_type" -b "/dev/sda1=:$fs_size" \
      --region "$EC2_REGION" -z "$EC2_AVAILABILITY_ZONE"
  `" &&
  \
  local instance_id="`
    echo "$instance_data" | grep ^INSTANCE | cut -d"$tab" -f2
  `"

  if [ -z "$instance_id" ]; then
    echo 'failed.' >&2
    fatal 'Failed to create instance'
  fi

  ec2-create-tags "$instance_id" \
    --tag Name="Nightly Build: Medic OS on `date +'%Y-%m-%d at %l:%M%P'`" \
    --tag Platform="$flavor_name" --tag Environment="$platform" \
    --tag Backup='false' --tag User="browndav" &>/dev/null && \
  \
  echo "done." >&2
  echo "Instance identifier: $instance_id"
  echo -n 'Discovering fully-qualified domain name... ' >&2
  \
  while [ -z "$external_fqdn" -a "$n" -gt 0 ]; do
    sleep 5 && n=$[$n - 1]
    local describe_data="`
      ec2-describe-instances "$instance_id" | grep ^PRIVATEIPADDRESS 
    `" &&
    local external_fqdn="`
      echo "$describe_data" | cut -d"$tab" -f4
    `"
  done

  if [ -z "$external_fqdn" ]; then
    echo 'failed.' >&2
    fatal 'Unable to discover host name for new instance'
  fi

  echo "done." >&2
  echo "Instance name: $external_fqdn"
  echo -n 'Waiting for instance to start... ' >&2

  local n='64'
  local rv='0'
  local ssh_id="$ssh_private_key_path"
  local cfg_dir='./medic-os/platform/config'
  local ssh_host="$flavor_user@$external_fqdn"

  while [ "$n" -gt 0 ]; do

    sleep 10 && n=$[n - 1]

    echo "$ssh_private_key_contents" | ssh_command  "$ssh_host" "$ssh_id" \
      'mkdir -p -- .ssh && cat >> .ssh/id_rsa' && \
    \
    echo 'done.' >&2 &&
    echo -n 'Establishing connection to instance... ' >&2 &&
    \
    ssh_command "$ssh_host" "$ssh_id" \
      "mkdir -p -- '$cfg_dir' && ln -sf aws-defaults '$cfg_dir/aws'" &&
    \
    echo "$settings" | ssh_command  "$ssh_host" "$ssh_id" \
      "mkdir -p -- '$cfg_dir/aws-defaults' &&
       cat > '$cfg_dir/aws-defaults/settings'" && \
    \
    ssh_command  "$ssh_host" "$ssh_id" \
      "echo 'done.' >&2 &&
         echo 'Connection established successfully.' >&2 &&
         echo -n 'Setting up environment... ' >&2 &&
         \
         export TZ='$time_zone' &&
         source '$cfg_dir/aws/settings' &&
         echo 'done.' >&2 &&
         \
         echo -n 'Resizing filesystem... ' >&2 &&
         sudo resize2fs /dev/xvda1 &>/dev/null &&
         echo 'done.' >&2 &&
         \
         echo -n 'Updating system package lists... ' >&2 &&
         sudo $flavor_update_command &>/dev/null &&
         echo 'done.' >&2 &&
         \
         echo -n 'Upgrading system packages... ' >&2 &&
         sudo $flavor_upgrade_command &>/dev/null &&
         echo 'done.' >&2 &&
         \
         echo 'Downloading Medic OS core:' >&2 &&
         curl -O# '$source_url/medic-os-core-src-latest.tar.xz' &&
         echo 'Downloading Medic OS JDK/JRE module:' >&2 &&
         curl -O# '$source_url/medic-os-java-$platform-latest.tar.xz' &&
         echo 'Downloading Medic OS EC2 API tools module:' >&2 &&
         curl -O# '$source_url/medic-os-ec2-api-tools-latest.tar.xz' &&
         \
         echo -n 'Extracting Medic OS core image... ' >&2 &&
         sudo tar xJf medic-os-core-src-latest.tar.xz &&
         echo 'done.' >&2 &&
         \
         echo -n 'Applying latest Medic OS updates... ' >&2 &&
         (cd medic-os/platform &&
           sudo git remote set-url origin "$vm_url" &&
           sudo git stash -q && sudo git pull -q) &&
         echo 'done.' >&2 &&
         \
         echo -n 'Installing build-time dependencies... ' >&2 &&
         sudo '$cfg_dir/$flavor/scripts/prepare-system' -qy &>/dev/null &&
         echo 'done.' >&2 &&
         \
         echo -n 'Extracting Medic OS JDK/JRE module... ' >&2 &&
         sudo tar xJf 'medic-os-java-$platform-latest.tar.xz' &&
         echo 'done.' >&2 &&
         \
         echo -n 'Extracting Medic OS EC2 API tools... ' >&2 &&
         sudo tar xJf medic-os-ec2-api-tools-latest.tar.xz &&
         echo 'done.' >&2 &&
         \
         cd medic-os &&
         sudo ln -nsf '$platform' java-current/selected &&
         \
         echo 'Starting Medic OS build process:' >&2 &&
         sudo make all \
           PLATFORM='$platform' $build_options &&
         \
         echo 'Medic OS build complete.' >&2 &&
         \
         echo 'Building EBS images:' >&2 &&
         ./platform/scripts/build-ebs-image \
           '../$cfg_dir/aws/settings' \
             '$platform' output/*'-$platform-xen' \
               'Medic OS Nightly $platform - `date +%Y%m%d`' /dev/xvdf && \
         \
         echo 'EBS images built successfully.' >&2 &&
         \
         echo 'Uploading ISO images:' >&2 &&
         ./platform/scripts/upload-iso-images \
           '../$cfg_dir/aws/settings' \
             '$platform' '`date +%Y%m%d`' 'nightly' &&
         \
         echo 'ISO images uploaded successfully.' && sync"

    rv="$?"

    if [ "$rv" -ne 255 ]; then
      break
    fi
  done

  if [ "$rv" -eq 255 ]; then
    echo 'timeout.' >&2
    fatal 'Failed to connect to instance; timeout exceeded'
  elif [ "$rv" -ne 0 ]; then
    echo && echo 'Remote build process failed.' >&2
  fi

  echo -n 'Pausing before instance termination... ' >&2

  if [ "$rv" -eq 0 ]; then
    sleep 10
  else
    sleep 90
  fi

  echo 'done.' >&2
  echo -n 'Terminating instance... ' >&2

  ec2-terminate-instances \
    "$instance_id" --region "$EC2_REGION" &>/dev/null \
      || fatal 'Failed to terminate instance'

  echo 'done.' >&2

  if [ "$rv" -ne 0 ]; then
    fatal 'Build process unsuccessful; no images created'
  fi
  
  echo 'Build complete.' >&2
  return 0
}

cd "$base_dir" \
  || fatal 'Unable to locate root directory'

source ./platform/scripts/include/aws \
  || fatal 'Unable to load one or more required libraries'

main "$@"
exit "$?"

