#!/bin/sh

self="`readlink -f "$0" 2>/dev/null || realpath "$0"`"
base_dir="`dirname "$self"`/.."

main()
{
  local m='node_modules'
  local prefix="$base_dir/packages/gardener/software/gardener/v1.0.4"

  rm -rf \
    "$prefix/$m/npm/doc" \
    "$prefix/$m/npm/man" \
    "$prefix/$m/npm/html" \
    "$prefix/$m/npm/$m/node-gyp" \
    "$prefix/$m/url/$m/punycode/vendor/requirejs/tests" \
    "$prefix/$m/url/$m/punycode/vendor/requirejs/dist/fonts"
}

main
exit "$?"

